CREATE TABLE IF NOT EXISTS users
(
    `id`         INT PRIMARY KEY AUTO_INCREMENT,
    `email`      VARCHAR(250) NOT NULL UNIQUE,
    `password`   VARCHAR(255) NOT NULL,
    `full_name`  VARCHAR(250) NOT NULL,
    `role`   VARCHAR(100) DEFAULT "user",
    `avatar` TEXT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );